<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Services\APIConsumption\" />
    <Folder Include="Services\ThirdParty\" />
    <Folder Include="Utilities\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" Version="13.1.0" />
    <PackageReference Include="GraphQL.EntityFramework" Version="27.2.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="RabbitMQ.Client" Version="7.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MedDemo.Application\MedDemo.Application.csproj" />
    <ProjectReference Include="..\MedDemo.Domain\MedDemo.Domain.csproj" />
  </ItemGroup>

</Project>
